from typing import Any, Dict, List, Literal, Optional, Union

from openai.types.chat.chat_completion_chunk import (
    ChatCompletionChunk,
    Choice,
    ChoiceDelta,
)
from openai.types.chat.chat_completion_message import Annotation
from pydantic import BaseModel


class PatchedChoiceDeltaCustomCallFunction(BaseModel):
    input: Optional[str] = None
    """
    Custom tool inputs.
    """

    name: Optional[str] = None
    """The name of the function to call."""


class PatchedChoiceDeltaToolCallFunction(BaseModel):
    arguments: Optional[str] = None
    """
    The arguments to call the function with, as generated by the model in JSON
    format. Note that the model does not always generate valid JSON, and may
    hallucinate parameters not defined by your function schema. Validate the
    arguments in your code before calling your function.
    """

    name: Optional[str] = None
    """The name of the function to call."""


class PatchedChoiceDeltaToolCall(BaseModel):
    index: Optional[int] = None

    id: Optional[str] = None
    """The ID of the tool call."""

    function: Optional[
        Union[
            PatchedChoiceDeltaToolCallFunction,
            PatchedChoiceDeltaCustomCallFunction,
        ]
    ] = None

    type: Optional[Literal["function", "custom"]] = None
    """The type of the tool. Monkey patching for `custom` support."""


# extend so we can use in streaming chunks
# with reasoning + citations + custom tools
class PatchedChatCompletionChunkChoiceDelta(ChoiceDelta):
    reasoning: Optional[str] = None
    """The contents of the chunk message."""

    reasoning_content: Optional[str] = None
    """The contents of the chunk message."""

    reasoning_summary: Optional[str] = None
    """The summary of the model's reasoning content."""

    annotations: Optional[List[Annotation]] = None
    """
    Annotations for the message, when applicable, as when using the
    [web search tool](https://platform.openai.com/docs/guides/tools-web-search?api-mode=chat).
    """

    tool_calls: Optional[List[PatchedChoiceDeltaToolCall]] = None  # type: ignore


class PatchedChatCompletionChunkChoice(Choice):
    delta: Union[PatchedChatCompletionChunkChoiceDelta, Dict[str, Any]]  # type: ignore


class PatchedChatCompletionChunk(ChatCompletionChunk):
    choices: List[PatchedChatCompletionChunkChoice]  # type: ignore
